type User @table {
  email: String!
  displayName: String!
  role: String!
  createdAt: Timestamp!
  phoneNumber: String
  photoUrl: String
}

type Order @table {
  recipientName: String!
  recipientAddress: String!
  status: String!
  createdAt: Timestamp!
  recipientPhone: String
  packageDescription: String
  scheduledDeliveryTime: Timestamp
  deliveredAt: Timestamp
  assignedDriver: User
}

type Route @table {
  name: String!
  date: Date!
  status: String!
  createdAt: Timestamp!
  description: String
  startedAt: Timestamp
  completedAt: Timestamp
  driver: User
}

type RouteOrder @table(key: ["route", "order"]) {
  positionInRoute: Int!
  createdAt: Timestamp!
  deliveryNotes: String
  route: Route!
  order: Order!
}

type ProofOfDelivery @table {
  type: String!
  createdAt: Timestamp!
  photoUrl: String
  signatureUrl: String
  notes: String
  order: Order
}